name 'blp-redis'
version '1.0.0'
maintainer 'Bloomberg Infrastructure Engineering'
maintainer_email 'chef@bloomberg.net'
license 'Apache-2.0'
description 'Installs and configures redis.'
long_description 'Installs and configures redis.'

issues_url 'https://github.com/bloomberg-cookbooks/redis/issues'
source_url 'https://github.com/bloomberg-cookbooks/redis'
chef_version '>= 12.5'

supports 'redhat', '>= 6.0'
supports 'centos', '>= 6.0'
supports 'ubuntu', '>= 12.04'

depends 'build-essential'
depends 'poise-archive', '~> 1.3'
depends 'poise-service', '~> 1.0'
depends 'yum-epel'
